// <auto-generated />
using System;
using Abuvi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abuvi.API.Migrations
{
    [DbContext(typeof(AbuviDbContext))]
    [Migration("20260313113925_AddIsActiveToFamilyUnits")]
    partial class AddIsActiveToFamilyUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Abuvi.API.Features.Camps.AssociationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasDatabaseName("IX_AssociationSettings_SettingKey");

                    b.ToTable("association_settings", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.Camp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbuviContactedAt")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("abuvi_contacted_at");

                    b.Property<bool?>("AbuviHasDataErrors")
                        .HasColumnType("boolean")
                        .HasColumnName("abuvi_has_data_errors");

                    b.Property<string>("AbuviLastVisited")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("abuvi_last_visited");

                    b.Property<Guid?>("AbuviManagedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("abuvi_managed_by_user_id");

                    b.Property<string>("AbuviPossibility")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("abuvi_possibility");

                    b.Property<string>("AccommodationCapacityJson")
                        .HasColumnType("text")
                        .HasColumnName("accommodation_capacity_json");

                    b.Property<string>("AdministrativeArea")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administrative_area");

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("BusinessStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_status");

                    b.Property<string>("ContactCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_company");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_person");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("ExternalSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("external_source_id");

                    b.Property<string>("FormattedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("formatted_address");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("google_maps_url");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal?>("GoogleRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("google_rating");

                    b.Property<int?>("GoogleRatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("google_rating_count");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastGoogleSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_google_sync_at");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NationalPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("national_phone_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PlaceTypes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("place_types");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<decimal>("PricePerAdult")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_adult");

                    b.Property<decimal>("PricePerBaby")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_baby");

                    b.Property<decimal>("PricePerChild")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_child");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("SecondaryWebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("secondary_website_url");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street_address");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("VatIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("vat_included");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("AbuviManagedByUserId");

                    b.HasIndex("ExternalSourceId")
                        .HasDatabaseName("ix_camps_external_source_id");

                    b.HasIndex("GooglePlaceId")
                        .HasDatabaseName("ix_camps_google_place_id");

                    b.ToTable("camps", null, t =>
                        {
                            t.HasCheckConstraint("CK_Camps_Latitude", "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)");

                            t.HasCheckConstraint("CK_Camps_Longitude", "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)");

                            t.HasCheckConstraint("CK_Camps_PricePerAdult", "price_per_adult >= 0");

                            t.HasCheckConstraint("CK_Camps_PricePerBaby", "price_per_baby >= 0");

                            t.HasCheckConstraint("CK_Camps_PricePerChild", "price_per_child >= 0");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.HasIndex("CampId")
                        .HasDatabaseName("ix_camp_audit_logs_camp_id");

                    b.HasIndex("CampId", "ChangedAt")
                        .HasDatabaseName("ix_camp_audit_logs_camp_id_changed_at");

                    b.ToTable("camp_audit_logs", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccommodationCapacityJson")
                        .HasColumnType("text")
                        .HasColumnName("accommodation_capacity_json");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CustomAdultMinAge")
                        .HasColumnType("integer")
                        .HasColumnName("custom_adult_min_age");

                    b.Property<int?>("CustomBabyMaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("custom_baby_max_age");

                    b.Property<int?>("CustomChildMaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("custom_child_max_age");

                    b.Property<int?>("CustomChildMinAge")
                        .HasColumnType("integer")
                        .HasColumnName("custom_child_min_age");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("ExtrasPaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extras_payment_deadline");

                    b.Property<DateTime?>("FirstPaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_payment_deadline");

                    b.Property<DateOnly?>("HalfDate")
                        .HasColumnType("date")
                        .HasColumnName("half_date");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<int?>("MaxWeekendCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_weekend_capacity");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("PricePerAdult")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_adult");

                    b.Property<decimal?>("PricePerAdultWeek")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_adult_week");

                    b.Property<decimal?>("PricePerAdultWeekend")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_adult_weekend");

                    b.Property<decimal>("PricePerBaby")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_baby");

                    b.Property<decimal?>("PricePerBabyWeek")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_baby_week");

                    b.Property<decimal?>("PricePerBabyWeekend")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_baby_weekend");

                    b.Property<decimal>("PricePerChild")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_child");

                    b.Property<decimal?>("PricePerChildWeek")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_child_week");

                    b.Property<decimal?>("PricePerChildWeekend")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_child_weekend");

                    b.Property<string>("ProposalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("proposal_notes");

                    b.Property<string>("ProposalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proposal_reason");

                    b.Property<DateTime?>("SecondPaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("second_payment_deadline");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("UseCustomAgeRanges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("use_custom_age_ranges");

                    b.Property<DateOnly?>("WeekendEndDate")
                        .HasColumnType("date")
                        .HasColumnName("weekend_end_date");

                    b.Property<DateOnly?>("WeekendStartDate")
                        .HasColumnType("date")
                        .HasColumnName("weekend_start_date");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CampId", "Year")
                        .HasDatabaseName("IX_CampEditions_CampId_Year");

                    b.ToTable("camp_editions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CampEditions_CustomAgeRanges", "NOT use_custom_age_ranges OR (custom_baby_max_age IS NOT NULL AND custom_child_min_age IS NOT NULL AND custom_child_max_age IS NOT NULL AND custom_adult_min_age IS NOT NULL)");

                            t.HasCheckConstraint("CK_CampEditions_PricePerAdult", "price_per_adult >= 0");

                            t.HasCheckConstraint("CK_CampEditions_PricePerBaby", "price_per_baby >= 0");

                            t.HasCheckConstraint("CK_CampEditions_PricePerChild", "price_per_child >= 0");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEditionAccommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccommodationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accommodation_type");

                    b.Property<Guid>("CampEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_edition_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CampEditionId");

                    b.ToTable("camp_edition_accommodations", null, t =>
                        {
                            t.HasCheckConstraint("CK_CampEditionAccommodations_Capacity", "capacity IS NULL OR capacity > 0");

                            t.HasCheckConstraint("CK_CampEditionAccommodations_SortOrder", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEditionExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_edition_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("PricingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pricing_period");

                    b.Property<string>("PricingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pricing_type");

                    b.Property<bool>("RequiresUserInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_user_input");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserInputLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_input_label");

                    b.HasKey("Id");

                    b.HasIndex("CampEditionId");

                    b.ToTable("camp_edition_extras", null, t =>
                        {
                            t.HasCheckConstraint("CK_CampEditionExtras_MaxQuantity", "max_quantity IS NULL OR max_quantity > 0");

                            t.HasCheckConstraint("CK_CampEditionExtras_Price", "price >= 0");

                            t.HasCheckConstraint("CK_CampEditionExtras_SortOrder", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Season")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("season");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("CampId")
                        .HasDatabaseName("ix_camp_observations_camp_id");

                    b.ToTable("camp_observations", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribution_name");

                    b.Property<string>("AttributionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attribution_url");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsOriginal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_original");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("PhotoReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_reference");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("CampId")
                        .HasDatabaseName("ix_camp_photos_camp_id");

                    b.HasIndex("CampId", "IsPrimary")
                        .HasDatabaseName("ix_camp_photos_camp_id_is_primary");

                    b.ToTable("camp_photos", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.FamilyUnits.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allergies");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("FamilyUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_unit_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("medical_notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relationship");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyUnitId");

                    b.HasIndex("UserId");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.FamilyUnits.FamilyUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("FamilyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("family_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_url");

                    b.Property<Guid>("RepresentativeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FamilyNumber")
                        .IsUnique()
                        .HasFilter("family_number IS NOT NULL");

                    b.HasIndex("RepresentativeUserId")
                        .IsUnique();

                    b.ToTable("family_units", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Guests.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("FamilyUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("FamilyUnitId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Abuvi.API.Features.MediaItems.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_location_id");

                    b.Property<string>("Context")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Decade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("decade");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<Guid?>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Context")
                        .HasDatabaseName("ix_media_items_context");

                    b.HasIndex("MemoryId")
                        .HasDatabaseName("ix_media_items_memory_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_media_items_uploaded_by_user_id");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_media_items_year");

                    b.HasIndex("IsApproved", "IsPublished")
                        .HasDatabaseName("ix_media_items_approved_published");

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Memberships.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MemberNumber")
                        .HasColumnType("integer")
                        .HasColumnName("member_number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId")
                        .IsUnique();

                    b.HasIndex("MemberNumber")
                        .IsUnique()
                        .HasFilter("member_number IS NOT NULL");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Memberships.MembershipFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "Year")
                        .IsUnique();

                    b.ToTable("membership_fees", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Memories.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<Guid?>("CampLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_location_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_memories_author_user_id");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_memories_year");

                    b.HasIndex("IsApproved", "IsPublished")
                        .HasDatabaseName("ix_memories_approved_published");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text")
                        .HasColumnName("admin_notes");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ConceptLinesSerialized")
                        .HasColumnType("text")
                        .HasColumnName("concept_lines");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_reference");

                    b.Property<int>("InstallmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("installment_number");

                    b.Property<bool>("IsManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manual");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("ProofFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("proof_file_name");

                    b.Property<string>("ProofFileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("proof_file_url");

                    b.Property<DateTime?>("ProofUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proof_uploaded_at");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransferConcept")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transfer_concept");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("IX_Payments_RegistrationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Payments_Status");

                    b.HasIndex("TransferConcept")
                        .HasDatabaseName("IX_Payments_TransferConcept");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AdminModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admin_modified_at");

                    b.Property<decimal>("BaseTotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_total_amount");

                    b.Property<Guid>("CampEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_edition_id");

                    b.Property<string>("CampatesPreference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("campates_preference");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("ExtrasAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("extras_amount");

                    b.Property<Guid>("FamilyUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_unit_id");

                    b.Property<bool>("HasPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_pet");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_user_id");

                    b.Property<string>("SpecialNeeds")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("special_needs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CampEditionId")
                        .HasDatabaseName("IX_Registrations_CampEditionId");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Registrations_Status");

                    b.HasIndex("FamilyUnitId", "CampEditionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Registrations_FamilyUnitId_CampEditionId");

                    b.ToTable("registrations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Registrations_TotalAmount", "total_amount = base_total_amount + extras_amount");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.RegistrationAccommodationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampEditionAccommodationId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_edition_accommodation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PreferenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("preference_order");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.HasKey("Id");

                    b.HasIndex("CampEditionAccommodationId");

                    b.HasIndex("RegistrationId", "CampEditionAccommodationId")
                        .IsUnique()
                        .HasDatabaseName("IX_RegAccommPrefs_RegistrationId_AccommodationId");

                    b.HasIndex("RegistrationId", "PreferenceOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_RegAccommPrefs_RegistrationId_PreferenceOrder");

                    b.ToTable("registration_accommodation_preferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegAccommPrefs_PreferenceOrder", "preference_order >= 1 AND preference_order <= 3");
                        });
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.RegistrationExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CampDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("camp_duration_days");

                    b.Property<Guid>("CampEditionExtraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_edition_extra_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UserInput")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_input");

                    b.HasKey("Id");

                    b.HasIndex("CampEditionExtraId");

                    b.HasIndex("RegistrationId", "CampEditionExtraId")
                        .IsUnique()
                        .HasDatabaseName("IX_RegistrationExtras_RegistrationId_CampEditionExtraId");

                    b.ToTable("registration_extras", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.RegistrationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AgeAtCamp")
                        .HasColumnType("integer")
                        .HasColumnName("age_at_camp");

                    b.Property<string>("AgeCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("age_category");

                    b.Property<string>("AttendancePeriod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("Complete")
                        .HasColumnName("attendance_period");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<string>("GuardianDocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guardian_document_number");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guardian_name");

                    b.Property<decimal>("IndividualAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("individual_amount");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<DateOnly?>("VisitEndDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_end_date");

                    b.Property<DateOnly?>("VisitStartDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_start_date");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("IX_RegistrationMembers_RegistrationId");

                    b.HasIndex("RegistrationId", "FamilyMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_RegistrationMembers_RegistrationId_FamilyMemberId");

                    b.ToTable("registration_members", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expiry");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<Guid?>("FamilyUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_unit_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_DocumentNumber")
                        .HasFilter("document_number IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Abuvi.API.Features.Users.UserRoleChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleChangeLogs");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.Camp", b =>
                {
                    b.HasOne("Abuvi.API.Features.Users.User", "AbuviManagedByUser")
                        .WithMany()
                        .HasForeignKey("AbuviManagedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AbuviManagedByUser");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampAuditLog", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.Camp", "Camp")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEdition", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.Camp", "Camp")
                        .WithMany("Editions")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEditionAccommodation", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.CampEdition", "CampEdition")
                        .WithMany("Accommodations")
                        .HasForeignKey("CampEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampEdition");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEditionExtra", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.CampEdition", "CampEdition")
                        .WithMany("Extras")
                        .HasForeignKey("CampEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampEdition");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampObservation", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.Camp", "Camp")
                        .WithMany("Observations")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampPhoto", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.Camp", "Camp")
                        .WithMany("Photos")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("Abuvi.API.Features.FamilyUnits.FamilyMember", b =>
                {
                    b.HasOne("Abuvi.API.Features.FamilyUnits.FamilyUnit", null)
                        .WithMany()
                        .HasForeignKey("FamilyUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Abuvi.API.Features.FamilyUnits.FamilyUnit", b =>
                {
                    b.HasOne("Abuvi.API.Features.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Abuvi.API.Features.FamilyUnits.FamilyUnit", "RepresentativeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Abuvi.API.Features.Guests.Guest", b =>
                {
                    b.HasOne("Abuvi.API.Features.FamilyUnits.FamilyUnit", "FamilyUnit")
                        .WithMany()
                        .HasForeignKey("FamilyUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyUnit");
                });

            modelBuilder.Entity("Abuvi.API.Features.MediaItems.MediaItem", b =>
                {
                    b.HasOne("Abuvi.API.Features.Memories.Memory", "Memory")
                        .WithMany("MediaItems")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Abuvi.API.Features.Users.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Abuvi.API.Features.Memberships.Membership", b =>
                {
                    b.HasOne("Abuvi.API.Features.FamilyUnits.FamilyMember", "FamilyMember")
                        .WithOne()
                        .HasForeignKey("Abuvi.API.Features.Memberships.Membership", "FamilyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamilyMember");
                });

            modelBuilder.Entity("Abuvi.API.Features.Memberships.MembershipFee", b =>
                {
                    b.HasOne("Abuvi.API.Features.Memberships.Membership", "Membership")
                        .WithMany("Fees")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Abuvi.API.Features.Memories.Memory", b =>
                {
                    b.HasOne("Abuvi.API.Features.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.Payment", b =>
                {
                    b.HasOne("Abuvi.API.Features.Registrations.Registration", "Registration")
                        .WithMany("Payments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.Registration", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.CampEdition", "CampEdition")
                        .WithMany()
                        .HasForeignKey("CampEditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.FamilyUnits.FamilyUnit", "FamilyUnit")
                        .WithMany()
                        .HasForeignKey("FamilyUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.Users.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CampEdition");

                    b.Navigation("FamilyUnit");

                    b.Navigation("RegisteredByUser");
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.RegistrationAccommodationPreference", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.CampEditionAccommodation", "CampEditionAccommodation")
                        .WithMany()
                        .HasForeignKey("CampEditionAccommodationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.Registrations.Registration", "Registration")
                        .WithMany("AccommodationPreferences")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampEditionAccommodation");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.RegistrationExtra", b =>
                {
                    b.HasOne("Abuvi.API.Features.Camps.CampEditionExtra", "CampEditionExtra")
                        .WithMany()
                        .HasForeignKey("CampEditionExtraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.Registrations.Registration", "Registration")
                        .WithMany("Extras")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampEditionExtra");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.RegistrationMember", b =>
                {
                    b.HasOne("Abuvi.API.Features.FamilyUnits.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.Registrations.Registration", "Registration")
                        .WithMany("Members")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Abuvi.API.Features.Users.UserRoleChangeLog", b =>
                {
                    b.HasOne("Abuvi.API.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abuvi.API.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.Camp", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Editions");

                    b.Navigation("Observations");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Abuvi.API.Features.Camps.CampEdition", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("Abuvi.API.Features.Memberships.Membership", b =>
                {
                    b.Navigation("Fees");
                });

            modelBuilder.Entity("Abuvi.API.Features.Memories.Memory", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Abuvi.API.Features.Registrations.Registration", b =>
                {
                    b.Navigation("AccommodationPreferences");

                    b.Navigation("Extras");

                    b.Navigation("Members");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
